# -*- coding: utf-8 -*-
"""add 'ing' at end of string

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukDmop4-MRvo22GzYFWGqMg0IgkwA0Jq
"""

n = input("Enter the string:")
if n[-3:] == 'ing':
	n = n+'ly'
else:
	n = n+'ing'
print(n)