# -*- coding: utf-8 -*-
"""ascending and descending

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OHq8zz1V-SiiatK-ohYQJqcUAg8x_A8k
"""

a = {'Lucy': 20, 'Mary': 30, 'Aljo': 25, 'Kristo': 23}
print("Dictionary : ",a)
print("ascending order using keys : ",sorted(a.keys()))
print("ascending order using values : ",sorted(a.values()))
print("descending order using keys :",sorted(a.keys(),reverse=True))
print("descending order using values :",sorted(a.values(),reverse=True))
print("ascending order using keys and values :",sorted(a.items()))
print("descending order using keys and values :",sorted(a.items(),reverse=True))