# -*- coding: utf-8 -*-
"""average of set of integers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16xI_iJNGXxVbhUmrmo5lc4kany5gT6-c
"""

n=int(input("Enter the number"))
sum=0
for i in range(1, n+1):
  a=int(input("Enter the number"))
  sum=sum+a
avg= sum/n
print("Average is",avg)