# -*- coding: utf-8 -*-
"""factorial using recursion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bwZlckqjgSbTiNgZymVswlc5W5ztUoFJ
"""

def rec_fact(n):
   if n == 1:
       return n
   else:
       return n*rec_fact(n-1)

num =int(input("enter the number"))
if num < 0:
   print(" factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   print("The factorial of", num, "is", rec_fact(num))