# -*- coding: utf-8 -*-
"""fibonacci series using recursion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvciYrrkIwSA-shfBTKN00afrkgzF6Ls
"""

def recur_fibo(n):
   if n <= 1:
       return n
   else:
       return(recur_fibo(n-1) + recur_fibo(n-2))

nterms = int(input("Enter the number: "))


if nterms <= 0:
   print("Plese enter a positive integer")
else:
   print("Fibonacci sequence:")
   for i in range(nterms):
       print(recur_fibo(i))