# -*- coding: utf-8 -*-
"""find simple interest

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otgwhpUQZDcm0jkKHK2vB0op7pcfXA4c
"""

principle=float(input("Enter the principle amount:"))
time=int(input("Enter the time:"))
rate=float(input("Enter the rate:"))
si=(principle*rate*time)/100
print("Simple interest:",si)