# -*- coding: utf-8 -*-
"""greatest of 2 numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-YJSvv9M13bQzX7hHhvmVEOFxlCxA07u
"""

a=int(input("Enter the first number"))
b=int(input("Enter the second number"))
if(a>b):
    print("a is greatest")
else:
    print("b is greatest")