# -*- coding: utf-8 -*-
"""length of longest word

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1utWzKS4IcWA_nKysymfXWGe6yhLrfYdm
"""

a =[]
n = int(input("Enter the number of words:"))
for i in range(0, n):
	m = input("Enter the word:")
	a.append(m)
max_length =len(a[0])
temp=a[0]
for i in a:
	if (len(i)>max_length):
		max_length=len(i)
		temp=i
print("Longest word is:",temp)
print("Length of longest word is:",max_length)