# -*- coding: utf-8 -*-
"""list of student record using dictionary

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fg8j9t1ZDH4YJ8MosxzOEJqnP9gI4gX6
"""

n=int(input("Enter the number of students:"))
studlist=[]
for i in range(0,n):
	stud={}
	stud['name']=input("Enter name:\n")
	stud["branch"]=input("Enter branch:\n")
	stud["roll no"]=int(input("Enter roll no:\n"))
	studlist.append(stud)
print("Name  Branch  Roll no")
print()
print()
for i in range(0,n):	
	print(studlist[i])