# -*- coding: utf-8 -*-
"""list of students in alphabetic order

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ewb25ECIn59i3aL1_yMR6K7yP7XpupMm
"""

stud={}
n=int(input("Enter the no. of students:"))
for i in range(0,n):
	a=input("Enter the name of student:")
	stud[a]=int(input("Enter the mark of student:"))
print(stud)
b=[]
b+=stud.keys()
b.sort()
for i in range(n):
	print("%s\t\t\t%d" %(b[i],stud[b[i]]))