# -*- coding: utf-8 -*-
"""no. of characters in a string

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E0pPBBwVIKCuVEHynqBocgv4YJifQ3uL
"""

s=input("Enter a string:")
freq={}
for i in s:
  if i in freq:
    freq[i]=freq[i]+1
  else:
    freq[i]=1
print("Count at each character is",s ,"is:\n",str(freq))