# -*- coding: utf-8 -*-
"""occurance of a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m9V-6c8KoVLqSnnpcK4M5AYVcN_Ew-VP
"""

def occur(str):
  count=0
  str1=input("Enter the string:")
  my_char="a"
  for i in str1:
    if i==my_char:
      count=count+1
  print("The occurance of a is",count)
occur(str)