# -*- coding: utf-8 -*-
"""power of number using recursion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XFyr3hJHajpXKPM2_VCyozS5peAVuSRO
"""

def power(base,exp):
    if(exp==1):
        return(base)
    if(exp!=1):
        return(base*power(base,exp-1))
base=int(input("Enter base: "))
exp=int(input("Enter exponential value: "))
print("Result:",power(base,exp))