# -*- coding: utf-8 -*-
"""swap 2 string @ position 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18muXXGv970lUtaeqNEtt2nZX_QX53_zV
"""

str1=input("Enter string 1: ")
str2=input("Enter string 2: ")
x=str1.replace(str1[0:1],str2[0:1])
y=str2.replace(str2[0:1],str1[0:1])
s=x+" "+y
print("After swapping:",s)